### PR TITLE
Fix of 3G on first and second sim

### PR DESCRIPTION
**Pull request by Deepflex**
Fix of 3G on first and second sim

### CODE REVIEW

**Comment by ferhung-mtk** [comment]
I didn't find this flag in source. Did u use your own RIL?

**Comment by Deepflex** [comment]
My RIL from Stock ROM. Not custom, and this line solve problem of 3g on 1 and 2 sim on 100%

**Comment by ferhung-mtk** [comment]
It seems not working.

**Comment by janengelmohr** [comment]
Tested, doesn't work.

**Pull request closed without merging**
