### PR TITLE
updation for creating for  necessary directory when builded.

### PR DESCRIPTION
**Pull request by diparthshah**
full credits goes to @hyperion70

### CODE REVIEW

**Comment by ferhung-mtk** [comment]
Good job. I deleted that code in libtinysala to pass it.

**Comment by diparthshah** [comment]
Building From Your sources , hoping to get booted on my device.

**Comment by diparthshah** [comment]
Also need to update some path in BoardConfig.mk for full build.

**Comment by waseemmaya** [comment]
Good luck diparth it will surely boot in your device. 👍

**Comment by waseemmaya** [comment]
Leave bugs

**Comment by lordarcadius** [comment]
Diparth shah which kernel sources you are going to use?

**Comment by ferhung-mtk** [comment]
You all guys don't forget to use the new vendor method. Or you won't boot.

**Comment by ferhung-mtk** [comment]
The “patch” DIR is not for boot necessarily. It is for advant setting.

**Comment by diparthshah** [comment]
@Rohan Taneja

**Comment by karthik9700459464** [comment]
Good luck

**Comment by diparthshah** [comment]
@ferhung-mtk i am using ur vendor tree so there should be no issue in booting correct ?

**Comment by ferhung-mtk** [comment]
I couldn't tell that i do not have your device. That is just a method for you to learn.

**Comment by diparthshah** [comment]
@ferhung-mtk 

i am using ur source code , getting few erros.
please look into it : http://hastebin.com/axevotuzul.vbs

**Comment by ferhung-mtk** [comment]
Sorry, I can't open the link. Push your main error here.

**Comment by diparthshah** [comment]
@ferhung-mtk can u upload your compiled rom ?

**Comment by ferhung-mtk** [comment]
http://pan.baidu.com/share/link?shareid=3734075115&uk=1193956335

**Comment by waseemmaya** [comment]
Thanks @ferhung-mtk
edit: I cant access this site, m unable to downlad this rom from pan.baidu.com.
http://pan.baidu.com/share/link?shareid=3734075115&uk=1193956335
please @ferhung-mtk upload it to another host.
thanks.

**Comment by hyperion70** [comment]
@ferhung-mtk
I'm need to apply all patch for build ?
https://github.com/ferhung-mtk/android_device_Xiaomi_HM2014011/blob/cm-13.0/patch/README.md
Thanks.

**Comment by ferhung-mtk** [comment]
No, you don't. This is improvement for settings.

**Comment by ferhung-mtk** [comment]
Some devices can't boot with selinux, so you shuold revert this commit: https://github.com/ferhung-mtk/android_system_core/commit/cc854eae6a4e1037fad244f9aadd8fec5286bd58

**Comment by diparthshah** [comment]
Sir @ferhung-mtk , still after updating sourve to upstream i am still facing issue as mentioned by me in previous comment , it will be helpful for me if u update u r current source. 
- Thanks

**Comment by ferhung-mtk** [comment]
I updated all, yesterday. I complied it yesterday, too. Getting no error. You should check your source still on newest situation.

Maybe you should repo init again.

**Comment by diparthshah** [comment]
okk sir @ferhung-mtk 
 should i initiate repository using your default.xml or should i sync it directly from cm github.  ???

**Comment by ferhung-mtk** [comment]
You must use my default.xml to init your source. To much things had been changed for MTK.

**Comment by diparthshah** [comment]
okkk sir :-)

**Comment by degrus** [comment]
@ferhung-mtk can u upload your newest compiled rom ? i  mean with bluetooth and wifi fixed and ril optimisation

**Comment by ferhung-mtk** [comment]
@degrus These are not fixed completely, yet. It also have lots of bugs. And I don't have too much time to do that. You all people can fix by yourselves.

**Comment by ferhung-mtk** [comment]
Sorry, I forget to merge fire855 commit, then you will have some building error.
Here is the link:
https://github.com/fire855/android_frameworks_base-mtk/commit/1faf4982eda20b7592a9816cad629782bf1eb4af

**Comment by diparthshah** [comment]
@ferhung-mtk getting error while applying patch from patch folder !!

http://hastebin.com/ogipabusod.avrasm

**Comment by ferhung-mtk** [comment]
You don't need to path that path! It is a  improvement for setting. It hasn't been updated for a long time. Maybe i should delete it.

**Comment by diparthshah** [comment]
@ferhung-mtk  can u help me in this issue ??

http://hastebin.com/uhawikisoc.coffee

**Comment by ferhung-mtk** [comment]
@diparthshah You shuold add the path manually. Or you just drop the path and delete which has been added. IN CASE, you can repo sync again after deleting all source.

**Pull request merged**
